#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ls='ls -GF'
alias sl=ls
alias cp='cp -i'
alias h='fc -l 0 -1'
alias hg='fc -l 0 -1|egrep'
#alias chrome='google-chrome >/dev/null 2>/dev/null &'
export LESS='-i -g -M -R -W'
export PAGER=less
export MANPAGER=less 
#export PATH=$HOME/dlsave/idea-IU-139.659.2/bin:$PATH
#export PATH=$HOME/Android/Sdk/platform-tools:$PATH
#if [ "$GUAKE_AS_STARTUP_APPLICATION" = true ]; then
#	GUAKE_AS_STARTUP_APPLICATION=false tmux new -s MAIN || tmux attach -t MAIN
#fi
#eval `dircolors ~/.dircolors`
#cd $HOME

