#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ls='ls -F'
alias sl=ls
alias chrome='google-chrome >/dev/null 2>/dev/null &'
alias less='less +Gg'
export MANPAGER='less +Gg'
export PATH=$HOME/Android/Sdk/platform-tools:$PATH

